[package]
name = "calcula_thor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
precedence = {git = "https://github.com/7M351/precedence.git", rev="v0.1"}
